sudo: required
language: python
services:
- docker
env:
  global:
  - ECR_REPO=clientesapp
  - AWS_REGION="us-east-1"
  - secure: travisEncryptedAWS_ACCOUNT_ID
  - secure: travisEncryptedAWS_ACCESS_KEY_ID
  - secure: travisEncryptedAWS_SECRET_ACCESS_KEY
before_install:
- pip install awscli
- export PATH=$PATH:$HOME/.local/bin
- aws configure set default.region $AWS_REGION
- aws ecr get-login-password >> ~/pass.txt
- cat ~/pass.txt | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/python:3.8.0-alpine
script:
- docker build -t $ECR_REPO .
deploy:
  provider: script
  script: bash deploy-ecr.sh
branches:
  only:
    - main
    - qa