sudo: required
language: python
services:
- docker
env:
  global:
  - ECR_REPO=clientesapp
  - AWS_REGION="us-east-1"
  - secure: travisEncryptedAWS_ACCOUNT_ID
  - secure: travisEncryptedAWS_ACCESS_KEY_ID
  - secure: travisEncryptedAWS_SECRET_ACCESS_KEY
before_install:
- pip install awscli
- export PATH=$PATH:$HOME/.local/bin
script:
- docker build -t $ECR_REPO .
deploy:
  provider: script
  script: bash deploy-ecr.sh
branches:
  only:
    - main
    - qa